### ISSUE TITLE
C++ example for the Rust Ownership is not corresponds to Ruby's one

### ISSUE THREAD

**Issue by pravic** [steveklabnik/history-of-rust#2]
Since in Ruby values are pointers, lets rewrite example with the following:

``` cpp
#include <iostream>
#include <vector>
#include <string>
#include <memory>

int main() {
    std::vector<std::shared_ptr<std::string>> v;

    v.push_back(std::make_shared<std::string>("Hello"));

    auto x = v[0];

    v.push_back(std::make_shared<std::string>("world"));

    std::cout << *x;
}
```

[Ideone.com](http://ideone.com/iDlCfM)

:wink:

**Comment by steveklabnik** [comment]
Ah, but this also isn't the same; Ruby does not use atomic reference counting to manage the lifetime.

Anyway, this is a presentation, so it's not really going to change. Thanks though!

**Comment by pravic** [comment]
ARC is not significant here.

**Comment by steveklabnik** [comment]
It's how `shared_ptr` works.
