### ISSUE TITLE
The Repository URL is 404

### ISSUE THREAD

**Issue by gfx** [steveklabnik/history-of-rust#4]
The Repository URL (`steveklabnik.com`'s) is 404. 
<img width="577" alt="Screen Shot 2020-02-03 at 10 06 41" src="https://user-images.githubusercontent.com/101800/73618719-f93a9600-466c-11ea-883d-1594f444f2ce.png">

Now it is http://steveklabnik.github.io/history-of-rust/ right?

**Comment by steveklabnik** [comment]
That is true, I've fixed it now, thank you!
